apiVersion: v1
kind: Pod
metadata:
  name: frontend-app
  labels:
    name: frontend-app
spec:
  containers:
  - name: frontend-app
    image: harry
    imagePullPolicy: Never
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8081
